
import { Mod, Skin } from './types';

export const AUTHOR_AVATARS: Record<string, string> = {
  'mega_biel10': 'https://i.postimg.cc/Z911nshF/image.png',
  'sexy shrek': 'https://api.dicebear.com/7.x/avataaars/svg?seed=sexyshrek&backgroundColor=c0aede',
  'Bonkunph': 'https://i.postimg.cc/wzCPyTrb/2-removebg-preview.png',
  '♠ Mai ღ.cpp': 'https://i.postimg.cc/hG5JNqt4/Design-sem-nome-10-1-removebg-preview.png',
};

export const MOCK_MODS: Mod[] = [
  {
    id: 'purebdcraft',
    title: 'PureBDcraft',
    description: 'A comic book style texture pack that transforms your Minecraft world into a vibrant and stylized experience.',
    author: '♠ Mai ღ.cpp',
    downloads: 0,
    follows: 0,
    updated: new Date().toISOString().split('T')[0],
    categories: ['Stylized', 'HD'],
    iconUrl: 'https://i.postimg.cc/SR0hzgg0/pack.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://drive.google.com/drive/folders/1PQPqDYFUqSogPCAO7rKVhNv62JjPfZNu?usp=drive_link'
  },
  {
    id: 'immersive-interface',
    title: 'Immersive Interface',
    description: 'A brand new immersive interface texture pack for a cleaner and more engaging UI experience.',
    author: 'sexy shrek',
    downloads: 0,
    follows: 0,
    updated: new Date().toISOString().split('T')[0],
    categories: ['UI'],
    iconUrl: 'https://i.postimg.cc/cJmZ271Q/pack.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/rikepsu5z82d2po/immersive_interface.zip/file'
  },
  {
    id: 'spawned-eggs',
    title: 'Spawned Eggs',
    description: 'Adds new spawn eggs to the game, allowing you to spawn various mobs easily.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Utility'],
    iconUrl: 'https://i.postimg.cc/4K1Sf2y0/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/1wwk8wx93brk1mq/Spawned_Eggs.zip/file'
  },
  {
    id: 'transparent-shield',
    title: 'Transparent Shield',
    description: 'Makes the shield transparent so it doesn\'t block your view during combat.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Utility', 'UI'],
    iconUrl: 'https://i.postimg.cc/JyRp23xg/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/yvuwzx8vqu9cz5h/Transparent_Shield.zip/file'
  },
  {
    id: 'bare-bones-plus',
    title: 'Bare Bones+',
    description: 'An enhanced version of the popular Bare Bones texture pack, simplifying textures for a cleaner look.',
    author: 'mega_biel10 and sexy shrek',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like', 'Simple'],
    iconUrl: 'https://i.postimg.cc/14bJQ1Mq/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/xj0598zhd0xj344/Bare_Bones%2B.zip/file'
  },
  {
    id: 'bare-bones-modern-ui',
    title: 'Bare Bones+ X Dark UI',
    description: 'Combines the Bare Bones+ texture pack with a sleek, dark user interface.',
    author: 'mega_biel10, sexy shrek and Bonkunph',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like', 'UI', 'Dark UI', 'Simple'],
    iconUrl: 'https://i.postimg.cc/v18vzYH8/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/beokekespn66iqj/Bare_Bones%2B_X_Modern_UI.zip/file'
  },
  {
    id: 'bare-bones-better-leaves',
    title: 'Bare Bones Better Leaves',
    description: 'Adds better leaf textures to the Bare Bones pack for more realistic foliage.',
    author: 'mega_biel10 and sexy shrek',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Realistic', 'Simple'],
    iconUrl: 'https://i.postimg.cc/bdn11DHd/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/hlj19027uw3ijy2/Bare_Bones_Better_Leaves.zip/file'
  },
  {
    id: 'vanilla-plus-modern-ui',
    title: 'Vanilla Plus x Dark UI',
    description: 'Enhances the vanilla experience with subtle improvements and a dark UI overhaul.',
    author: 'mega_biel10 and Bonkunph',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like', 'UI', 'Dark UI'],
    iconUrl: 'https://i.postimg.cc/zyxhqn52/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/ra971yjirvlvaxk/Vanilla_Plus_x_Modern_UI.zip/file'
  },
  {
    id: 'vanilla-plus',
    title: 'Vanilla Plus',
    description: 'A pure Vanilla Plus experience, improving textures while keeping the original feel.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like'],
    iconUrl: 'https://i.postimg.cc/QKgBw70Y/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/z92u4fkkeebsihz/Vanilla_Plus.zip/file'
  },
  {
    id: 'low-fire-water-fog',
    title: 'Low Fire & Water Fog',
    description: 'Reduces fire height and water fog for better visibility.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Utility'],
    iconUrl: 'https://i.postimg.cc/1gLfzBdV/e8117f4c.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/3kft3k2c51k3fk1/low_fire_%26_water_fog.zip/file'
  },
  {
    id: 'actions-stuff',
    title: 'Actions & Stuff 1.5',
    description: 'A port of Actions and Stuff for MCPSP.\nWARNING: this texture does not contain animations!!!',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Realistic'],
    iconUrl: 'https://i.postimg.cc/NyrjZT0f/image.png',
    version: '1.5',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/8fshok6enr26f21/actions_%2526_stuff_1.5.zip/file'
  },
  {
    id: 'classical-art-plus',
    title: 'Classical Art+',
    description: 'Replaces paintings with classical art pieces for a more sophisticated look.',
    author: 'Bonkunph',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like'],
    iconUrl: 'https://i.postimg.cc/n9TFqG36/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/y63kjkjnw3iuatt/Classical_Art%2B.zip/file'
  },
  {
    id: 'cubic-sun-moon',
    title: 'Cubic Sun & Moon',
    description: 'Changes the sun and moon to be cubic, matching the blocky aesthetic of the game.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like'],
    iconUrl: 'https://i.postimg.cc/bDcQskVm/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/6cuj7ebdy0ltmm1/Cubic_Sun_%26_Moon.zip/file'
  },
  {
    id: 'fast-better-grass',
    title: 'Fast Better Grass',
    description: 'Improves grass textures for better performance and visuals.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Realistic'],
    iconUrl: 'https://i.postimg.cc/cvvYhXVv/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/wj2qbsaswfvnsgh/Fast_Better_Grass.zip/file'
  },
  {
    id: 'clean-water',
    title: 'Clean Water',
    description: 'Makes water clearer and more transparent for better underwater visibility.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Utility', 'Realistic'],
    iconUrl: 'https://i.postimg.cc/z3pg1sN3/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/iy9l7298rmsazmh/clean_water.zip/file'
  },
  {
    id: 'new-spawn-eggs',
    title: 'New Spawn Eggs',
    description: 'Updated textures for spawn eggs to match modern Minecraft versions.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Vanilla Like'],
    iconUrl: 'https://i.postimg.cc/TLfpz9HH/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/hspdgbsnuau6blt/new_spawn_eggs.zip/file'
  },
  {
    id: 'more-visible-ores',
    title: 'More Visible Ores',
    description: 'Highlights ores with borders or brighter colors to make mining easier.',
    author: 'mega_biel10',
    downloads: 0,
    follows: 0,
    updated: '2024-03-01',
    categories: ['Utility'],
    iconUrl: 'https://i.postimg.cc/KRw4GFHz/image.png',
    version: '1.0',
    license: 'Unknown',
    loader: 'Lamecraft',
    zipUrl: 'https://www.mediafire.com/file/3b53ehid21634wb/more_visible_ores.zip/file'
  }
];

export const MOCK_SKINS: Skin[] = [
  { id: '1', name: 'Steve Classic', imageUrl: 'https://raw.githubusercontent.com/minecraft-js/skinview3d/master/assets/1.8_texture.png', views: 5000, downloads: 0, tags: ['Classic'] },
  { id: '2', name: 'Alex', imageUrl: 'https://raw.githubusercontent.com/minecraft-js/skinview3d/master/assets/alex_texture.png', views: 8900, downloads: 0, tags: ['Slim', 'Classic'] },
  { id: '3', name: 'Technoblade', imageUrl: 'https://raw.githubusercontent.com/bs-community/skinview3d/master/examples/img/skin.png', views: 1200, downloads: 0, tags: ['Youtuber', 'Crown'] },
  { id: '4', name: 'Iron Man', imageUrl: 'https://raw.githubusercontent.com/bs-community/skinview3d/master/examples/img/ironman_texture.png', views: 15000, downloads: 0, tags: ['Marvel', 'Hero'] },
  { id: '5', name: 'Diamond King', imageUrl: 'https://raw.githubusercontent.com/minecraft-js/skinview3d/master/assets/1.8_texture.png', views: 3200, downloads: 0, tags: ['PvP', 'Blue'] },
  { id: '6', name: 'Mudkip', imageUrl: 'https://raw.githubusercontent.com/minecraft-js/skinview3d/master/assets/alex_texture.png', views: 7600, downloads: 0, tags: ['Pokemon', 'Blue'] },
  { id: '7', name: 'Link', imageUrl: 'https://raw.githubusercontent.com/bs-community/skinview3d/master/examples/img/skin.png', views: 9000, downloads: 0, tags: ['Games', 'Nintendo'] },
  { id: '8', name: 'Mario', imageUrl: 'https://raw.githubusercontent.com/bs-community/skinview3d/master/examples/img/ironman_texture.png', views: 11000, downloads: 0, tags: ['Games', 'Nintendo'] },
];

export const GEMINI_SYSTEM_INSTRUCTION = `You are an expert on Minecraft PSP Homebrew history and modding. 
You know about Lamecraft, DSP Craft, CrossCraft, and various legacy homebrews. 
You can suggest mods, explain how to install them on a PSP Memory Stick (ms0:/PSP/GAME/), and generate creative ideas for skins.
Keep responses concise and helpful.`;
